project:
  type: website
  
website:
  comments:
    giscus:
      repo: PracticeOrientedAICDT/pro_ai_hub
      theme:  preferred_color_scheme

  navbar:
    search: true
    right:
      - text: "Home"
        file: index.qmd
      - text: "Blog"
        file: blog.html
      - text: "Researchers"
        file: researchers.qmd 
      - text: "Newsletter"
        file: newsletter.qmd  
      - text: "Events"
        file: event_calendar.qmd
      - about.qmd 
  
format:
  html:
    theme: default
    css: styles.css
    toc: true



