project:
  type: website

website:
  comments:
    giscus:
      repo: DelmiroDaladier/icr
      theme:  preferred_color_scheme

  navbar:
    background: primary
    search: true
    right:
      - text: "Home"
        file: index.qmd
      - text: "Blog"
        file: blog.html
      - about.qmd 

title-block-banner: true      
format:
  html:
    page-layout: article
    theme: 
      light: cosmo
      dark: cyborg
    css: styles.css
    toc: true



